language: julia
julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'cd(Pkg.dir("GeometricalPredicates")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(Coveralls.process_folder())';
